services:
  redis:
    image: redis:8.8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
